### ISSUE TITLE
[Feature Request] error(s) logging

### ISSUE THREAD

**Issue by typhoon71** [dteviot/DriveByEditor#2]
I'd like to ask for a little feature.
Right now webtoepub will tell you there were errors here and there when grabbing, at the moment the error happens (like,  for an image link).
It would be nice if those "report" were also available later, as a log, possibly in the same directory as the epub.
Would this be possible?

**Comment by dteviot** [comment]
Yes, it should be possible.
That said, I think you should put this issue against WebToEpub, not the DriveByEditor

**Comment by typhoon71** [comment]
Right, often doing too many things at the same time results in failure for some of them if not all of them... Sorry.
